function [HX, HXY, HlX, HlXY, HiX, HiXY, ChiX, HshX, HshXY] = xtrploop(X, pars)
%%% *function [HX, HXY, HlX, HlXY, HiX, HiXY, ChiX, HshX, HshXY] = xtrploop(X, pars)*
%%%
%%% ### Description
%%% Loops over iterations of the extrapolation procedure.
%%%
%%% ### Inputs:
%%% - *X*: *nDimensions x nTrials x nStimuli* array including response data.
%%% - *pars*: parameter structure to check generated by build_parameters_structure.
%%%
%%% ### Outputs:
%%% - *HX*: estimate of H(X).
%%% - *HXY*: estimate of H(X|Y).
%%% - *HlX*: estimate of H_lin(X).
%%% - *HlXY*: estimate of H_lin(X|Y).
%%% - *HiX*: estimate of H_ind(X).
%%% - *HiXY*: estimate of H_ind(X|Y).
%%% - *ChiX*: estimate of Chi(X).
%%% - *HshX*: estimate of H_shuffle(X).
%%% - *HshXY*: estimate of H_shuffle(X|Y).
%%%
% ### Further notes:
%
%   Copyright (C) 2010 Cesare Magri
%   Version: 1.0.0
%
% -------
% LICENSE
% -------
% This software is distributed free under the condition that:
% 1. it shall not be incorporated in software that is subsequently sold;
% 2. the authorship of the software shall be acknowledged and the following article shall be properly cited in any publication that uses results generated by the software:
%
%      Magri C, Whittingstall K, Singh V, Logothetis NK, Panzeri S: A
%      toolbox for the fast information analysis of multiple-site LFP, EEG
%      and spike train recordings. BMC Neuroscience 2009 10(1):81;
%
% 3.  this notice shall remain in place in each source file.
%
% ----------
% DISCLAIMER
% ----------
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

% Try to make the XTRP=1 case as fast as possible:
if pars.xtrp==1
    [HX, HXY, HlX, HlXY, HiX, HiXY, ChiX, HshX, HshXY] = ...
            quadratic_extrapolation(X, pars);
        
else
    HX    = 0;
    HXY   = 0; 
    HlX   = 0;
    HlXY  = 0;
    HiX   = 0;
    HiXY  = 0;
    ChiX  = 0;
    HshX  = 0;
    HshXY = 0;

    for k=1:pars.xtrp
        [HXtmp, HXYtmp, HlXtmp, HlXYtmp, HiXtmp, HiXYtmp, ChiXtmp, HshXtmp, HshXYtmp] = ...
            quadratic_extrapolation(X, pars);

        HX    = HX    + HXtmp    ./ pars.xtrp; 
        HXY   = HXY   + HXYtmp   ./ pars.xtrp;
        HlX   = HlX   + HlXtmp   ./ pars.xtrp;
        HlXY  = HlXY  + HlXYtmp  ./ pars.xtrp;
        HiX   = HiX   + HiXtmp   ./ pars.xtrp;
        HiXY  = HiXY  + HiXYtmp  ./ pars.xtrp;
        ChiX  = ChiX  + ChiXtmp  ./ pars.xtrp;
        HshX  = HshX  + HshXtmp  ./ pars.xtrp;
        HshXY = HshXY + HshXYtmp ./ pars.xtrp;
    end
end
