function direct_method

%%% DIRECT_METHOD Estimate entropy quantities with direct method.
%%%
%%% This function is the direct method engine of called by ENTROPY and its
%%% related functions.
%%%
%%% USAGE
%%%
%%%   [HX, HXY, HlX, HlXY, HiX, HiXY, ChiX, HshX, HshXY] = direct_method(X, nt, pars);
%%%
%%%
%%% INPUTS
%%%
%%%   X    - response matrix
%%%   pars - parameters structure
%%%


%%% *function direct_method*
%%%
%%% ### Description
%%% Estimate entropy quantities with direct method. This function is the direct method engine of called by ENTROPY and its related functions.
%%%
%%% ### Inputs:
%%% - *X*: *nDimensions x nTrials x nStimuli* array including response data.
%%% - *pars*: parameter structure to check generated by build_parameters_structure.
%%%
%%% ### Outputs:
%%% - *HX*: direct estimate of H(X).
%%% - *HXY*: direct estimate of H(X|Y).
%%% - *HlX*: direct estimate of H_lin(X).
%%% - *HlXY*: direct estimate of H_lin(X|Y).
%%% - *HiX*: direct estimate of H_ind(X).
%%% - *HiXY*: direct estimate of H_ind(X|Y).
%%% - *ChiX*: direct estimate of Chi(X).
%%% - *HshX*: direct estimate of H_shuffle(X).
%%% - *HshXY*: direct estimate of H_shuffle(X|Y).
%%%
%%% ### Further notes:
%%%
%%% The parameters structure must include the following fields:
%%%
%%% =========================================================================
%%% | FIELD NAME       | TYPE          | DESCRIPTION                        |
%%% =========================================================================
%%% | pars.nt          | numeric array | number of trials per stimulus.     |
%%% |-----------------------------------------------------------------------|
%%% | pars.biasCorrNum | scalar value  | bias correction number:            |
%%% |                  |               |                                    |
%%% |                  |               |  -1 : user-defined bias            |
%%% |                  |               |       correction routine           |
%%% |                  |               |                                    |
%%% |                  |               |   2 : Panzeri & Treves             |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHX        | logical value | flag specifying whether H(X) needs |
%%% |                  |               | to be estimated                    |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHXY       | logical value | flag specifying whether H(X|Y)     |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHlX       | logical value | flag specifying whether H_lin(X)   |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHlXY      | logical value | flag specifying whether H_lin(X|Y) |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHiX       | logical value | flag specifying whether H_ind(X)   |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHiXY      | logical value | flag specifying whether H_ind(X|Y) |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doChiX      | logical value | flag specifying whether Chi(X)     |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHshX      | logical value | flag specifying whether H_sh(X)    |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.doHshXY     | logical value | flag specifying whether H_sh(X|Y)  |
%%% |                  |               | needs to be estimated              |
%%% |-----------------------------------------------------------------------|
%%% | pars.testMode    | logical value | flag specifying whther test-mode   | 
%%% |                  |               | has been selected                  |
%%% =========================================================================
%%%
%%% Zero is returned for all outputs corresponding to output options that were not selected by the user.
%%%
% REMARK!
% As for all the functions in the toolbox, the difference between the quantities H_lin(X|Y) and H_ind(X|Y) is kept in this function. See the "REMARKS FOR DEVELOPERS" note in function ENTROPY.
%
% Copyright (C) 2010 Cesare Magri
% Version 6a
%
% -------
% LICENSE
% -------
% This software is distributed free under the condition that:
% 1. it shall not be incorporated in software that is subsequently sold;
% 2. the authorship of the software shall be acknowledged and the following article shall be properly cited in any publication that uses results generated by the software:
%
%      Magri C, Whittingstall K, Singh V, Logothetis NK, Panzeri S: A
%      toolbox for the fast information analysis of multiple-site LFP, EEG
%      and spike train recordings. BMC Neuroscience 2009 10(1):81;
%
% 3.  this notice shall remain in place in each source file.
%
% ----------
% DISCLAIMER
% ----------
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

